namespace KCPlayer.Plugin.TestVod
{
    public enum VodUrlType
    {
        Ftp,
        Magnet,
        LocalBt,
        WebBt,
        BtHash,
        Hash,
        Ed2K,
        QQdl,
        Flashget,
        Thunder,
        Web,
        Qvod,
        Ffdycc,
        None,
        Kuai,
        KuaiXunlei,
        Youku,
        Qiyi,
        Tudou,
        Vqq,
        YinFuFlash,
        Flash,
        M1905
    }
}